# diffusion_policy/config/task/real_xarm_image.yaml
name: real_xarm_image

image_shape: [3, 224, 224]          # 3-channel images after resizing to 224x224

## HPC ##
dataset_path: /home/n10813934/data/diffusion/converted_padded     # path to the root of your dataset (episodes directories)
# dataset_path: /home/n10813934/data/diffusion     # path to the root of your dataset (episodes directories)

## BASE LAPTOP ##
# dataset_path: /home/d_pad25/Thesis/Data/diffusion_test/test_data    # path to the root of your dataset (episodes directories)
# out_dir: /home/d_pad25/Thesis/Data/diffusion_test/test_pad    # path to the output directory

## SSD ##
# dataset_path: /mnt/d/Sem2/diffusion/data_test
# out_dir: /mnt/d/Sem2/diffusion/data_out

## WORK LAPTOP ##
# dataset_path: /mnt/d/Data/Sem2/Round_1/gello    # path to the root of your dataset (episodes directories)
# out_dir: /mnt/d/Data/Sem2/diffusion/converted_padded    # path to the output directory
# dataset_path: /mnt/d/Data/Sem2/diffusion/data_test    # path to the root of your dataset (episodes directories)
# out_dir: /mnt/d/Data/Sem2/diffusion/data_out    # path to the output directory


shape_meta: &shape_meta
  obs:
    wrist_rgb:
      shape: ${task.image_shape}
      type: rgb         # image from wrist camera
    base_rgb:
      shape: ${task.image_shape}
      type: rgb         # image from base camera
    robot_state:
      shape: [7]        # 6 joints + 1 gripper position
      type: low_dim     # low-dimensional vector
  action:
    shape: [7]          # 6 joint commands + 1 gripper command

env_runner:
  _target_: diffusion_policy.env_runner.xarm6_image_runner.XArm6ImageRunner

dataset:
  _target_: diffusion_policy.dataset.real_xarm6_image_dataset.RealXArm6ImageDataset
  # _target_: diffusion_policy.dataset.real_xarm6_image_dataset_RAM_log.RealXArm6ImageDataset
  # _target_: diffusion_policy.dataset.real_xarm6_image_dataset_low_mem.RealXArm6ImageDataset # low memory version
  shape_meta: *shape_meta
  dataset_path: ${task.dataset_path}
  # work_store_kind: dir        # "dir" or "zip" for the cache file
  # mem_debug: true
  # out_dir: ${task.out_dir}     # COMMENT OUT IF TRAINING
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  n_obs_steps: ${dataset_obs_steps}
  n_latency_steps: ${n_latency_steps}
  use_cache: True                   # cache dataset in memory for speed (optional)
  seed: 42
  val_ratio: 0.1
  max_train_episodes: null
  delta_action: False
